apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: django-deployemnt
        image: adguchiya/apptodo
        ports:
        - containerPort: 8000
